name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Install Checkov
        run: pip install checkov
      
      - name: Run Checkov
        run: |
          checkov -d . \
            --soft-fail \
            --output cli \
            --quiet

      - name: Terraform Plan
        id: plan # step id for reference
        run: |
          terraform plan \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var="environment=dev" \
            -no-color 2>&1 | tee plan_output.txt

      - name: Post plan to PR
        run: |
          PLAN=$(cat plan_output.txt)
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "### Terraform Plan 📖
            \`\`\` 
            ${PLAN}
            \`\`\`  "
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
