name: Terraform Apply

on:
      push:
            branches: [main]
            paths:
                  - 'infra/**'
                  - '.github/workflows/**'

permissions:
      id-token: write
      contents: read

jobs:
      apply:
            runs-on: ubuntu-latest
            defaults:
                  run:
                        working-directory: infra

            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Setup Terraform
                    uses: hashicorp/setup-terraform@v3

                  - name: Configure AWS credentials
                    uses: aws-actions/configure-aws-credentials@v4
                    with:
                        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                        aws-region: us-east-1
                        audience: sts.amazonaws.com

                  - name: Terraform init
                    run: terraform init

                  - name: Terraform Format Check
                    run: terraform fmt -check -recursive

                  - name: Terraform Validate
                    run: terraform validate

                  - name: Terraform Apply
                    run: | 
                        terraform apply \
                              -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
                              -var="environment=dev" \
                              -auto-approve